merill/cmd

website/config/commands.csv

This brings the endpoint inline with other `ad*.cmd.ms` endpoints.

Use Entra for `ad.cmd.ms`

---

website/config/commands.csv

Links through to the Automation Account blade.

Add `azauto.cmd.ms`

---

website/config/commands.csv

Adding Azure Automanage

---

website/config/commands.csv

Add cmd for [SQL Managed Instance Blade](https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Sql%2FmanagedInstances) = `sqlmi`

Add cmd/alias for SQL Managed Instance - sqlmi

---

website/config/commands.csv

Adding support for B2B invitations.

Update commands csv to add support for B2B invite

---

website/config/commands.csv

I'm not really sure how you want to handle this one. It is the _Azure_ Cloud Shell, but it is a bit of a standalone app being embedded in the M365 admin portal and the Exchange Admin Center.

Add Azure Cloud Shell `azshell.cmd.ms`

---

website/config/commands.csv

adding short command for Azure AD Entitlement management

Updating command for ELM

---

website/config/commands.csv

Added links for Azure Policy, Azure Container Registries, Azure Container Instance, SSH Public Keys, Data Collection Rules, and Azure Arc for Servers (hybrid compute).

Added Policy,ACR,ACI,SSH,DCR,ARC

---

website/config/commands.csv

Add a few commonly hit Azure services
- azappinsights
- azloganalytics
- azvnet
- azservicebus
- azapplicationgateway
- azwaf
Add aliases
- azlb as `lb`
- azsa as `sa`
- azkv as `kv`

additional azure services - appinsights, loganalytics, vnet, servicebus, applicationgateway, waf

---

website/config/commands.csv

Added Outlook

---

website/config/commands.csv

Added Azure Firewall Manager and Public IP Addresses

Added additional Azure blades

---

website/config/commands.csv

Added Azure Preview Portal link

Azure Preview Portal

---

website/config/commands.csv

Add Azure Management Groups Blade Shortcut

Add Azure Management Groups Blade Shortcut

---

website/config/commands.csv

Adding command option for the Azure Machine Learning Studio landing page.

Added Azure Machine Learning Studio command

---

website/config/commands.csv

Adding command option for the Azure Resource Graph Explorer landing page.

Added Azure Resource Graph Explorer command

---

website/config/commands.csv

Adds several Azure endpoints:
- Managed Identities
- Service Health
- Create a Resource
- Network Watcher
- Azure Advisor
- Availability Sets
- Scale Sets

Add several Azure endpoints

---

website/config/commands.csv

Add Azure Update Management Center

Add Azure Update Management Center

---

website/config/commands.csv

This commit will add the Quarantine section.

Quarantine Emails

---

website/config/commands.csv

**Azure**
> ![image](https://user-images.githubusercontent.com/60783263/198720957-bae6e3fe-81e6-4e9b-ac8a-aa638afe86c0.png)
> _The name of the resource used in Azure CLI is quite longer than what we expect when we want to use a tool like `cmd.ms`_
**App Specific Blades / Pages**
**PR Checklist**

Add Azure PostgreSQL servers management

---

website/config/commands.csv

Add oct: Office Customization Tool command

---

website/config/commands.csv

Provided additional commands and URL endpoints associated with the "Azure Purview" and "Microsoft 365 Compliance" brand into the single Microsoft Purview brand name. This includes renaming existing commands, adding relevant legacy aliases and keywords as well as the associated endpoints for the Microsoft Purview compliance offerings.

Updates to Purview Unified Data Governance and Purview Compliance

---

website/config/commands.csv

Updated Purview nomenclature on a few of services

Updated Purview nomenclature

---

website/config/commands.csv

Hi @merill 
Proposing to add the Microsoft 365 Apps admin center portal, I did not see it listed. 
Let me know if you agree.

Adding M365 Apps Admin Center

---

website/config/commands.csv

Added q for quarantine alias and price or apc for Price Calculator

Quarantine alias and Price Calculator

---

website/config/commands.csv

Added DevOps portal link in the CSV at line no : 166
issue link: https://github.com/merill/cmd/issues/64

Added Devops portal link

---

website/config/commands.csv

See changes at https://learn.microsoft.com/da-dk/mem/intune/fundamentals/whats-new#week-of-march-6-2023

The Microsoft Intune admin center has a new URL

---

website/config/commands.csv

Added Universal Print console.

Add Universal Print console

---

website/config/commands.csv

Added cmd for Intune Troubleshooting.

Added cmd for Intune Troubleshooting.

---

website/config/commands.csv

In this PR, added link for Microsoft Forms and Microsoft Loop. 
This will also address issue #71

Added link for microsoft forms and loop

---

website/config/commands.csv

redirect for the Local Administrator Password Recovery blade in Azure AD

add adlaps for Local Administrator Password Recovery

---

website/config/commands.csv

Added https://lighthouse.microsoft.com/

Added Microsoft Lighthouse portal URL

---

website/config/commands.csv

See https://aka.ms/DeprecationFAQ (VLSC moving to MAC)

Added MAC Software Downloads and Volume License Keys (new VLSC)

---

website/config/commands.csv

Include Cosmos DB Explorer

---

website/config/commands.csv

Added some shortcuts to go directly to the panels in the EAC.
Might be worth adding a separate category for Exchange too at some point - currently these are listed in the Microsoft 365 category (with the ex.cmd.ms link also).

Added Exchange Mail flow rules and message trace

---

website/config/commands.csv

https://github.com/merill/cmd/issues/124

Add tenant switcher in M365 to commands

---

website/config/commands.csv

A really cool blade that gives you a great overview of your resources.

add Azure Resource Manager Blade

---

website/config/commands.csv

Link to the list of my Office / 365 licenses and subscriptions

My office account subscriptions and applications

---

website/config/commands.csv

I think it would be great to link to the anti phishing policies page :)

Add Anti-Phishing deep link

---

website/config/commands.csv

This one:
Not to be confused with "Consent and permissions" which has a similar URL (just above in the CSV file)

Add "User settings"

---

website/config/commands.csv

Added Entra Cloud Sync config blade

Added Entra Cloud Sync config blade

---

website/config/commands.csv

Added a link to the DKIM blade in Defender portal for email authentication settings

Added DKIM Defender Blade

---

website/config/commands.csv
website/docs/docs/contributing.md
website/docs/index.mdx

Changed naming of Azure AD to Entra ID

Azure AD to Entra ID

---

website/docs/docs/related.md

Fix tiny typo in related.md

---

website/config/commands.csv

Add azfd alias to the azfdcdn command

Add azfd alias

---

website/config/commands.csv

This is the Azure Guest Assignments blade. Note that the URL contains %2F encodings; this is required.

added Azure Guest Assignments URL. 

---

website/config/commands.csv

I added some more links for Defender related policies

add links for several Defender policies

---

website/config/commands.csv

Added the reports blade in Defender admin portal and all links inside it.

Added all Defender reports

---

website/config/commands.csv

Add School Data Sync to the commands list

Add School Data Sync

---

website/config/commands.csv

Updated the  Threat Intelligence URL as it's been deprecated. Closes #159

Update Threat Intelligence URL
